### ISSUE TITLE
Guide to searching/analysis

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/ms-text-analysis#2]
@njr2128: Ive started a web page to provide info on searching/analyzing the MS text data. It is here:
https://github.com/cu-mkp/ms-text-analysis/blob/master/guide_to_searching.md which is rendered for viewing at https://cu-mkp.github.io/ms-text-analysis/guide_to_searching (note: the embedded Voyant tools take a little while to load; be patient)

I'll probably split it up into several pages...

Please send any ideas, feedback, etc...

**Comment by njr2128** [comment]
This is great and a resource that is now included in the Sandbox https://github.com/cu-mkp/sandbox/edit/main/index.md
